{% set name = "gopass" %}
{% set version = "1.15.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gopasspw/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 00ad6a32f89fe64760b70b9424af19b88d671673a66424d59d80cfa97deb75d3

build:
  number: 0
  script:
    - make build
    - go-licenses save . --save_path license-files
    - make install  # [unix]
    # Copy the executable under Windows (`make install` does not work)
    - COPY gopass "%LIBRARY_BIN%\gopass.exe"  # [win]
    # Clear out cache to avoid file not removable warnings
    - chmod -R u+w $(go env GOPATH) && rm -r $(go env GOPATH)  # [unix]

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses
    - make

test:
  commands:
    - gopass --help

about:
  home: https://www.gopass.pw
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: The slightly more awesome standard unix password manager for teams.
  dev_url: https://github.com/gopasspw/gopass

extra:
  recipe-maintainers:
    - anjos
